"""add_daily_bias

Revision ID: 4aec54460bca
Revises: 8710c47ce693
Create Date: 2025-12-26 01:40:21.840539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aec54460bca'
down_revision: Union[str, None] = '8710c47ce693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_slots', sa.Column('use_daily_bias', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_slots', 'use_daily_bias')
    # ### end Alembic commands ###
