version: "3.8"
services:
  mt5_v2:
    image: gmag11/metatrader5_vnc:latest
    container_name: mt5-v2
    ports:
      - "3001:3000"
      - "8002:8001"
    environment:
      - CUSTOM_USER=trader
      - PASSWORD=trading
    volumes:
      - mt5_config_v2:/config
      # NOW add your local folder
      - type: bind
        source: ./portafolio_manager
        target: /config/.wine/drive_c/Program Files/MetaTrader 5/MQL5/Experts/portafolio_manager
        read_only: false
    networks:
      mt5_network_v2:
        ipv4_address: 10.13.13.20
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    restart: unless-stopped

volumes:
  mt5_config_v2:

networks:
  mt5_network_v2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.13.13.0/24