#!/usr/bin/env python3
"""
SQLite to PostgreSQL Migration Script

Migrates all data from SQLite database to PostgreSQL with proper data transformations.

Usage:
    python scripts/migrate_sqlite_to_postgres.py \
        --sqlite data/cv_agent.db \
        --postgres "postgresql://cv_agent:password@localhost:5432/cv_trading"
"""

import argparse
import sqlite3
import psycopg2
import psycopg2.extras
import json
from datetime import datetime
from typing import List, Tuple, Any


def convert_boolean(value: Any) -> bool:
    """Convert SQLite boolean (0/1) to PostgreSQL boolean."""
    if value is None:
        return None
    return bool(value)


def convert_json(value: Any) -> dict:
    """Convert JSON string to dict for JSONB fields."""
    if value is None:
        return None
    if isinstance(value, str):
        try:
            return json.loads(value)
        except json.JSONDecodeError:
            return None
    return value


def get_table_columns(cursor, table_name: str) -> List[str]:
    """Get column names for a table."""
    cursor.execute(f"SELECT * FROM {table_name} LIMIT 0")
    return [desc[0] for desc in cursor.description]


def migrate_table(sqlite_conn, pg_conn, table_name: str, transformations: dict = None):
    """
    Migrate a single table from SQLite to PostgreSQL.

    Args:
        sqlite_conn: SQLite connection
        pg_conn: PostgreSQL connection
        table_name: Name of table to migrate
        transformations: Dict of column_name -> transform_function
    """
    transformations = transformations or {}

    # Get data from SQLite
    sqlite_cursor = sqlite_conn.cursor()
    sqlite_cursor.execute(f"SELECT * FROM {table_name}")
    rows = sqlite_cursor.fetchall()

    if not rows:
        print(f"  ⚠ Table '{table_name}' is empty, skipping...")
        return 0

    # Get column names
    columns = get_table_columns(sqlite_cursor, table_name)

    # Transform data
    transformed_rows = []
    for row in rows:
        transformed_row = []
        for i, col_name in enumerate(columns):
            value = row[i]

            # Apply transformation if specified
            if col_name in transformations:
                value = transformations[col_name](value)

            transformed_row.append(value)
        transformed_rows.append(tuple(transformed_row))

    # Insert into PostgreSQL
    pg_cursor = pg_conn.cursor()

    # Exclude 'id' column from INSERT (auto-generated by SERIAL)
    insert_columns = [col for col in columns if col != 'id']
    placeholders = ', '.join([f'${i+1}' for i in range(len(insert_columns))])
    columns_str = ', '.join(insert_columns)

    insert_query = f"""
        INSERT INTO {table_name} ({columns_str})
        VALUES ({placeholders})
    """

    # Prepare data without 'id' column
    id_index = columns.index('id') if 'id' in columns else None
    insert_rows = []
    for row in transformed_rows:
        if id_index is not None:
            insert_row = list(row[:id_index]) + list(row[id_index+1:])
        else:
            insert_row = row
        insert_rows.append(tuple(insert_row))

    # Bulk insert using execute_batch for better performance
    psycopg2.extras.execute_batch(pg_cursor, insert_query, insert_rows, page_size=100)

    # Fix sequence for tables with SERIAL primary key
    if 'id' in columns:
        pg_cursor.execute(f"""
            SELECT setval(pg_get_serial_sequence('{table_name}', 'id'),
                         COALESCE((SELECT MAX(id) FROM {table_name}), 1),
                         true)
        """)

    pg_conn.commit()
    print(f"  ✓ Migrated {len(rows)} rows from '{table_name}'")
    return len(rows)


def migrate_database(sqlite_path: str, postgres_url: str):
    """Migrate entire database from SQLite to PostgreSQL."""
    print(f"\n🔄 Starting migration from SQLite to PostgreSQL")
    print(f"  Source: {sqlite_path}")
    print(f"  Target: {postgres_url.split('@')[1] if '@' in postgres_url else postgres_url}\n")

    # Connect to both databases
    sqlite_conn = sqlite3.connect(sqlite_path)
    pg_conn = psycopg2.connect(postgres_url)

    total_rows = 0

    # Define tables and their transformations
    tables_config = [
        {
            'name': 'market_data',
            'transforms': {}
        },
        {
            'name': 'models',
            'transforms': {
                'hyperparameters': convert_json,
                'is_active': convert_boolean
            }
        },
        {
            'name': 'training_runs',
            'transforms': {}
        },
        {
            'name': 'predictions',
            'transforms': {}
        },
        {
            'name': 'positions',
            'transforms': {
                'breakeven_set': convert_boolean,
                'partial_taken': convert_boolean,
                'trailing_active': convert_boolean
            }
        },
        {
            'name': 'killzone_windows',
            'transforms': {
                'is_active': convert_boolean
            }
        },
        {
            'name': 'trades',
            'transforms': {}
        },
        {
            'name': 'trading_config',
            'transforms': {}
        },
        {
            'name': 'system_logs',
            'transforms': {
                'details': convert_json
            }
        },
        {
            'name': 'portfolios',
            'transforms': {}
        },
        {
            'name': 'strategies',
            'transforms': {
                'config': convert_json
            }
        },
        {
            'name': 'portfolio_allocations',
            'transforms': {
                'is_active': convert_boolean
            }
        },
        {
            'name': 'portfolio_performance',
            'transforms': {}
        },
        {
            'name': 'signal_confirmations',
            'transforms': {
                'volume_confirmed': convert_boolean,
                'trend_confirmed': convert_boolean,
                'fibonacci_details': convert_json,
                'smc_details': convert_json,
                'validation_details': convert_json
            }
        },
        {
            'name': 'trade_cooldowns',
            'transforms': {}
        }
    ]

    # Migrate each table
    for table_config in tables_config:
        table_name = table_config['name']
        transforms = table_config['transforms']

        try:
            rows_migrated = migrate_table(sqlite_conn, pg_conn, table_name, transforms)
            total_rows += rows_migrated
        except Exception as e:
            print(f"  ✗ Error migrating '{table_name}': {e}")
            pg_conn.rollback()
            raise

    # Verify migration
    print(f"\n📊 Migration Summary:")
    print(f"  Total rows migrated: {total_rows}")

    # Verify row counts match
    print(f"\n🔍 Verifying data integrity...")
    sqlite_cursor = sqlite_conn.cursor()
    pg_cursor = pg_conn.cursor()

    all_match = True
    for table_config in tables_config:
        table_name = table_config['name']

        sqlite_cursor.execute(f"SELECT COUNT(*) FROM {table_name}")
        sqlite_count = sqlite_cursor.fetchone()[0]

        pg_cursor.execute(f"SELECT COUNT(*) FROM {table_name}")
        pg_count = pg_cursor.fetchone()[0]

        if sqlite_count == pg_count:
            print(f"  ✓ {table_name}: {sqlite_count} rows")
        else:
            print(f"  ✗ {table_name}: SQLite={sqlite_count}, PostgreSQL={pg_count} (MISMATCH!)")
            all_match = False

    # Close connections
    sqlite_conn.close()
    pg_conn.close()

    if all_match:
        print(f"\n✅ Migration completed successfully! All tables verified.")
    else:
        print(f"\n⚠️ Migration completed with mismatches. Please review.")


def main():
    parser = argparse.ArgumentParser(description='Migrate SQLite database to PostgreSQL')
    parser.add_argument('--sqlite', required=True, help='Path to SQLite database file')
    parser.add_argument('--postgres', required=True, help='PostgreSQL connection URL')
    args = parser.parse_args()

    try:
        migrate_database(args.sqlite, args.postgres)
    except KeyboardInterrupt:
        print("\n\n⚠️ Migration interrupted by user")
    except Exception as e:
        print(f"\n\n❌ Migration failed: {e}")
        raise


if __name__ == '__main__':
    main()
