"""Add institutional slot columns

Revision ID: 8710c47ce693
Revises: 
Create Date: 2025-12-25 23:53:38.763402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8710c47ce693'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_regimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('regime_type', sa.String(), nullable=False),
    sa.Column('trend_direction', sa.String(), nullable=True),
    sa.Column('volatility_level', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_regimes_id'), 'market_regimes', ['id'], unique=False)
    op.create_index(op.f('ix_market_regimes_symbol'), 'market_regimes', ['symbol'], unique=False)
    op.create_table('news_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('impact', sa.String(), nullable=False),
    sa.Column('forecast', sa.String(), nullable=True),
    sa.Column('previous', sa.String(), nullable=True),
    sa.Column('actual', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_events_date'), 'news_events', ['date'], unique=False)
    op.create_index(op.f('ix_news_events_id'), 'news_events', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('backtest_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('strategy_config', sa.JSON(), nullable=True),
    sa.Column('final_balance', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_sessions_id'), 'backtest_sessions', ['id'], unique=False)
    op.create_table('bot_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mt5_login', sa.String(), nullable=True),
    sa.Column('mt5_server', sa.String(), nullable=True),
    sa.Column('mt5_password_encrypted', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('symbol_type', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('risk_percent', sa.Float(), nullable=True),
    sa.Column('min_confluence_score', sa.Integer(), nullable=True),
    sa.Column('max_trades', sa.Integer(), nullable=True),
    sa.Column('swing_length', sa.Integer(), nullable=True),
    sa.Column('ob_lookback', sa.Integer(), nullable=True),
    sa.Column('fvg_min_size', sa.Float(), nullable=True),
    sa.Column('vp_lookback', sa.Integer(), nullable=True),
    sa.Column('use_adx_filter', sa.Boolean(), nullable=True),
    sa.Column('enable_vwap_strategy', sa.Boolean(), nullable=True),
    sa.Column('enable_stoch_strategy', sa.Boolean(), nullable=True),
    sa.Column('enable_institutional_strategy', sa.Boolean(), nullable=True),
    sa.Column('enable_fibonacci_strategy', sa.Boolean(), nullable=True),
    sa.Column('rsi_period', sa.Integer(), nullable=True),
    sa.Column('rsi_overbought', sa.Integer(), nullable=True),
    sa.Column('rsi_oversold', sa.Integer(), nullable=True),
    sa.Column('be_trigger', sa.Float(), nullable=True),
    sa.Column('trailing_sl', sa.Boolean(), nullable=True),
    sa.Column('trailing_step', sa.Float(), nullable=True),
    sa.Column('trailing_distance', sa.Float(), nullable=True),
    sa.Column('tsl_mode', sa.String(), nullable=True),
    sa.Column('tsl_activation_r', sa.Float(), nullable=True),
    sa.Column('tsl_atr_period', sa.Integer(), nullable=True),
    sa.Column('tsl_atr_multiplier', sa.Float(), nullable=True),
    sa.Column('tsl_chandelier_period', sa.Integer(), nullable=True),
    sa.Column('tsl_chandelier_mult', sa.Float(), nullable=True),
    sa.Column('tsl_swing_lookback', sa.Integer(), nullable=True),
    sa.Column('tsl_swing_buffer_atr', sa.Float(), nullable=True),
    sa.Column('tsl_psar_af_start', sa.Float(), nullable=True),
    sa.Column('tsl_psar_af_increment', sa.Float(), nullable=True),
    sa.Column('tsl_psar_af_max', sa.Float(), nullable=True),
    sa.Column('partial_tp_on', sa.Boolean(), nullable=True),
    sa.Column('partial_tp_amount', sa.Float(), nullable=True),
    sa.Column('tp_ratio', sa.Float(), nullable=True),
    sa.Column('sl_atr_multiplier', sa.Float(), nullable=True),
    sa.Column('max_trade_duration_hours', sa.Float(), nullable=True),
    sa.Column('max_spread', sa.Float(), nullable=True),
    sa.Column('trading_hours_start', sa.String(), nullable=True),
    sa.Column('trading_hours_end', sa.String(), nullable=True),
    sa.Column('daily_loss_limit_percent', sa.Float(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_signal_time', sa.DateTime(), nullable=True),
    sa.Column('max_portfolio_risk_percent', sa.Float(), nullable=True),
    sa.Column('max_positions_per_symbol', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_configs_id'), 'bot_configs', ['id'], unique=False)
    op.create_table('mt5_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password_encrypted', sa.String(), nullable=False),
    sa.Column('server', sa.String(), nullable=False),
    sa.Column('symbol_prefix', sa.String(), nullable=True),
    sa.Column('symbol_suffix', sa.String(), nullable=True),
    sa.Column('terminal_path', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('max_drawdown_percent', sa.Float(), nullable=True),
    sa.Column('max_daily_dd_percent', sa.Float(), nullable=True),
    sa.Column('starting_balance', sa.Float(), nullable=True),
    sa.Column('daily_starting_balance', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_connected', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mt5_accounts_id'), 'mt5_accounts', ['id'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_profit', sa.Float(), nullable=True),
    sa.Column('total_loss', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('largest_win', sa.Float(), nullable=True),
    sa.Column('largest_loss', sa.Float(), nullable=True),
    sa.Column('average_win', sa.Float(), nullable=True),
    sa.Column('average_loss', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_id'), 'performance_metrics', ['id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('trade_type', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit_1', sa.Float(), nullable=True),
    sa.Column('take_profit_2', sa.Float(), nullable=True),
    sa.Column('take_profit_3', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('risk_percent', sa.Float(), nullable=False),
    sa.Column('confluence_score', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_partially_closed', sa.Boolean(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('trade_type', sa.String(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('confluence_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['backtest_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_id'), 'backtest_trades', ['id'], unique=False)
    op.create_table('bot_config_accounts',
    sa.Column('bot_config_id', sa.Integer(), nullable=True),
    sa.Column('mt5_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bot_config_id'], ['bot_configs.id'], ),
    sa.ForeignKeyConstraint(['mt5_account_id'], ['mt5_accounts.id'], )
    )
    op.create_table('bot_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_config_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('direction_filter', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('confirmation_timeframe', sa.String(), nullable=True),
    sa.Column('trading_session', sa.String(), nullable=True),
    sa.Column('session_end_action', sa.String(), nullable=True),
    sa.Column('risk_percent', sa.Float(), nullable=True),
    sa.Column('tp_ratio', sa.Float(), nullable=True),
    sa.Column('sl_atr_multiplier', sa.Float(), nullable=True),
    sa.Column('use_adx_filter', sa.Boolean(), nullable=True),
    sa.Column('enable_vwap_strategy', sa.Boolean(), nullable=True),
    sa.Column('enable_stoch_strategy', sa.Boolean(), nullable=True),
    sa.Column('enable_institutional_strategy', sa.Boolean(), nullable=True),
    sa.Column('enable_fibonacci_strategy', sa.Boolean(), nullable=True),
    sa.Column('use_h1_trend_filter', sa.Boolean(), nullable=True),
    sa.Column('stoch_k_period', sa.Integer(), nullable=True),
    sa.Column('stoch_d_period', sa.Integer(), nullable=True),
    sa.Column('vwap_use_trend_filter', sa.Boolean(), nullable=True),
    sa.Column('rsi_period', sa.Integer(), nullable=True),
    sa.Column('rsi_overbought', sa.Integer(), nullable=True),
    sa.Column('rsi_oversold', sa.Integer(), nullable=True),
    sa.Column('enable_trailing_stop', sa.Boolean(), nullable=True),
    sa.Column('tsl_mode', sa.String(), nullable=True),
    sa.Column('tsl_activation_r', sa.Float(), nullable=True),
    sa.Column('partial_tp_on', sa.Boolean(), nullable=True),
    sa.Column('partial_tp_amount', sa.Float(), nullable=True),
    sa.Column('max_trade_duration_hours', sa.Float(), nullable=True),
    sa.Column('min_confluence_score', sa.Integer(), nullable=True),
    sa.Column('magic_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_config_id'], ['bot_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('magic_number')
    )
    op.create_index(op.f('ix_bot_slots_id'), 'bot_slots', ['id'], unique=False)
    op.create_table('execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_id'), 'execution_logs', ['id'], unique=False)
    op.create_table('risk_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_config_id', sa.Integer(), nullable=False),
    sa.Column('max_daily_loss', sa.Float(), nullable=True),
    sa.Column('max_total_dd', sa.Float(), nullable=True),
    sa.Column('profit_target', sa.Float(), nullable=True),
    sa.Column('current_risk_per_trade', sa.Float(), nullable=True),
    sa.Column('is_halted', sa.Boolean(), nullable=True),
    sa.Column('halt_reason', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_config_id'], ['bot_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_config_id')
    )
    op.create_index(op.f('ix_risk_profiles_id'), 'risk_profiles', ['id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('confluence_score', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_recommendation', sa.String(), nullable=True),
    sa.Column('trend', sa.String(), nullable=False),
    sa.Column('poc_level', sa.Float(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('was_executed', sa.Boolean(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_risk_profiles_id'), table_name='risk_profiles')
    op.drop_table('risk_profiles')
    op.drop_index(op.f('ix_execution_logs_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index(op.f('ix_bot_slots_id'), table_name='bot_slots')
    op.drop_table('bot_slots')
    op.drop_table('bot_config_accounts')
    op.drop_index(op.f('ix_backtest_trades_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_performance_metrics_id'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_mt5_accounts_id'), table_name='mt5_accounts')
    op.drop_table('mt5_accounts')
    op.drop_index(op.f('ix_bot_configs_id'), table_name='bot_configs')
    op.drop_table('bot_configs')
    op.drop_index(op.f('ix_backtest_sessions_id'), table_name='backtest_sessions')
    op.drop_table('backtest_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_news_events_id'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_date'), table_name='news_events')
    op.drop_table('news_events')
    op.drop_index(op.f('ix_market_regimes_symbol'), table_name='market_regimes')
    op.drop_index(op.f('ix_market_regimes_id'), table_name='market_regimes')
    op.drop_table('market_regimes')
    # ### end Alembic commands ###
