
import os
import pandas as pd
from datetime import datetime
import xml.etree.ElementTree as ET

class AutomationManager:
    def __init__(self, reports_dir="/reports"):
        self.reports_dir = reports_dir

    def generate_ini(self, 
                     expert="PortfolioManager\\Portfolio_Governor.mq5", 
                     symbol="XAUUSD", 
                     period="M15", 
                     deposit=10000, 
                     date_from="2024.01.01", 
                     date_to="2024.01.31",
                     model=1, # 0=EveryTick, 1=OHLC, 2=OpenPrices, 3=MathCalc, 4=RealTicks
                     ) -> str:
        """
        Generates the content for tester.ini.
        """
        # Note: Report path must be relative or absolute inside the container.
        # We mapped 'mt5_reports' volume to '/reports' in both containers.
        # But 'terminal64.exe' runs in Wine, so it sees '/reports' as 'Z:\reports' usually.
        # OR we can just output to C:\app\report.xml if we mapped it there.
        # Simpler: Output to C:\app\report.xml and then we move it or direct write to /reports if mapped.
        # Let's try writing directly to the mapped volume. 
        # In Container: /reports
        # In Wine: Z:\reports (likely)
        
        report_file = "report.xml"
        
        ini = f"""[Tester]
Expert=Experts\\{expert}
Symbol={symbol}
Period={period}
Deposit={deposit}
Leverage=1:100
Model={model}
ExecutionMode=0
Optimization=0
FromDate={date_from}
ToDate={date_to}
ForwardMode=0
Report=C:\\app\\{report_file}
ReplaceReport=1
ShutdownTerminal=1
"""
        return ini

    def parse_report(self, report_path="/reports/report.xml") -> pd.DataFrame:
        """
        Parses the XML report generated by MT5.
        Returns a DataFrame of trades.
        """
        # Note: The sidecar (mt5_server) wrote to C:\app\report.xml.
        # If we mapped /reports to the same volume, we need to know where C:\app is.
        # In docker-compose, we mapped ./ to /app.
        # So report.xml should be in current directory ./report.xml
        
        local_report_path = "report.xml"
        
        if not os.path.exists(local_report_path):
            return pd.DataFrame()
            
        try:
            tree = ET.parse(local_report_path)
            root = tree.getroot()
            
            # This depends on the exact XML structure of MT5 reports.
            # Usually <Report><Orders><Order ... /><Deals><Deal ... /></Deals>
            # We want Deals.
            
            deals = []
            for deal in root.findall(".//Deal"):
                deals.append(deal.attrib)
                
            df = pd.DataFrame(deals)
            return df
        except Exception as e:
            print(f"Error parsing report: {e}")
            return pd.DataFrame()
