FROM gmag11/metatrader5_vnc:latest

# Switch to root to ensure we can modify system files
USER root

# Copy our startup script to the custom init directory
# LSIO images run these scripts during container initialization
COPY startup.sh /custom-cont-init.d/99-sidecar

# Make it executable (CRITICAL for it to run)
RUN chmod +x /custom-cont-init.d/99-sidecar

# Also ensure pip is upgraded in the base image just in case
# (Though startup.sh handles this at runtime, doing it here saves time if building)
# Note: Wine environment is tricky during build, better to leave runtime install in startup.sh
# because the wine prefix /config/.wine might be created at runtime.

